typography_spectrum: 0.4892589
color:
  brandColors:
    - '#ffffff'
    - '#f9ccab'
    - '#5c91c3'
    - '#00294b'
    - '#a6660e'
  brandStrength: 0.5865975
  lightness: 0.697637
  saturation: 0.7244898
  rhythmicContrast: 0.6740065
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: AndyFixIt
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: This is a tagline
purpose: []
